postgres:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: <host>
      port: 5432
      user: postgres
      pass: <pass>
      dbname: postgres
      schema: public
    prod:
      type: postgres
      threads: 1
      host: <host>
      port: 5432
      user: postgres
      pass: <pass>
      dbname: postgres
      schema: public
  target: dev
  
databricks:
  outputs:
    dev:
      host: {HOST}
      http_path: {HTTP_PATH}
      schema: default
      threads: 1
      token: {TOKEN}
      type: databricks
  target: dev